Consumer_services/Consumer_services/urls.py
from django.contrib import admin
from django.urls import path

from gas_utility import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('submit_request/', views.submit_service_request, name='submit_request'),
    path('request_status/', views.request_status, name='request_status'),
]

Consumer_services/gas_utility/models.py
from django.db import models

#model for service request
class ServiceRequest(models.Model):
    STATUS_CHOICES = (
        ('Pending', 'Pending'),
        ('In Progress', 'In Progress'),
        ('Completed', 'Completed'),
    )
    REQUEST_TYPES = (
        ('Gas Leak', 'Gas Leak'),
        ('Meter Installation', 'Meter Installation'),
        ('Maintenance', 'Maintenance'),
        ('Gas Refill','Gas Refill')
    )

    request_type = models.CharField(max_length=100, choices=REQUEST_TYPES)
    details = models.TextField(null=True,blank=True)
    attachment = models.FileField(upload_to='attachments/', blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Pending')
    date_submitted = models.DateTimeField(auto_now_add=True)
    date_resolved = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.request_type} - {self.status}"

Consumer_services/gas_utility/forms.py
from django import forms
from .models import ServiceRequest

class ServiceRequestForm(forms.ModelForm):
    class Meta:
        model = ServiceRequest
        fields = ['request_type', 'details', 'attachment']

Consumer_services/gas_utility/views.py
from django.shortcuts import render, redirect
from .models import ServiceRequest
from .forms import ServiceRequestForm

#view for service_request
def submit_service_request(request):
    if request.method == 'POST':
        form = ServiceRequestForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('request_status')
    else:
        form = ServiceRequestForm()
    return render(request, 'gas_utility/service_request.html', {'form': form})

#view for request_status
def request_status(request):
    service_requests = ServiceRequest.objects.all()
    return render(request, 'gas_utility/request_status.html', {'service_requests': service_requests})

Consumer_services/templates/gas_utility/home.html
<!DOCTYPE html>
{%load static%}
{% load django_bootstrap5 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
     <title>{% block title %}My Website{% endblock %}</title>
            {% bootstrap_css %} {% bootstrap_javascript %}.
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        body
        {
            background:radial-gradient(circle at 18.7% 37.8%, rgb(250, 250, 250) 0%, rgb(225, 234, 238) 90%); display: flex;
            flex-direction: column;
            min-height: 100vh; /* This ensures that the content takes at least the full viewport height */
        }

        main
        {
            flex: 1; /* This allows the main content to grow and push the footer to the bottom */
        }
        nav
        {
            background-image:linear-gradient(to right,rgb(135, 206, 235),rgb(135, 206, 235));
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.5), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            opacity:0.8;
             z-index:99;
        }
        footer
        {
            background-image:linear-gradient(to right, rgb(135, 206, 235), rgb(135, 206, 235));
            text-align: center;
        }
        .footer-menu
        {
            float: center;
            display: flex;
            align-items: center;
            justify-content: center;
            margin: 1rem 0 0rem 0;
        }
        .footer-menu ul
        {
            display: flex;
        }
        .footer-menu ul li
        {
            padding-right: 30px;
            display: block;
        }
        .footer-menu ul li a
        {
            color: white;
            text-decoration: none;
        }
        .footer-menu ul li a:hover
        {
            color: #27bcda;
        }

        .btnpurple
        {
            border: 2px solid #800080;
            border-radius: 5px;
            color: #800080;
            padding: 8px 10px;
            font-size: 16px;
            cursor: pointer;
        }
        .btnpurple:hover
        {
        border-color: #800080;
        background: #800080;
        color: white;
        }
    </style>
</head>
<body>
<nav class="navbar fixed-top navbar-expand-lg  p-3 mb-2 mix-black-40 text-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#" style="text-shadow: 1px 1px 2px black, 0 0 25px blue, 0 0 5px darkblue;color:white">Gas Utility</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link " aria-current="page" href="" target="_self" style="color:black;">Home</a>
            <a class="nav-link" href="{% url 'submit_request' %}" style="color:black;" >Service request</a>
            <a class="nav-link" href="{% url 'request_status' %}" style="color:black;">Status</a>
      </div>
    </div>
  </div>
</nav>
<main>
    {% block content %}{% endblock %}
  </main>
<footer>
    <!-- Your common footer content goes here -->
    <p>&copy; 2024 Gas Utility. All rights reserved.<u>Always at your service</u></p>
      <div class="footer-menu">
                <ul class="f-menu">
                    <li><a class="nav-link" href="" style="color:black;">Home</a></li>

				</ul>
      </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

Consumer_services/templates/gas_utility/request_status.html
{% extends 'gas_utility/home.html' %}
{% block content %}
<div class="container mt-4">
        <div class="row justify-content-center my-5">
            <div class="col-md-12">
    <h2>Request Status</h2>
    <table  class="table table-striped">
        <thead>
            <tr>
                <th>Request Type</th>
                <th>Status</th>
                <th>Date Submitted</th>
                <th>Date Resolved</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            {% for service_request in service_requests %}
            <tr>
                <td>{{ service_request.request_type }}</td>
                <td>{{ service_request.status }}</td>
                <td>{{ service_request.date_submitted }}</td>
                <td>{{ service_request.date_resolved }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
            </div>
        </div>
</div>
{% endblock %}

Consumer_services/templates/gas_utility/service_request.html
{% extends 'gas_utility/home.html' %}
{% block content %}

<div class="container mt-4">
        <div class="row justify-content-center my-5">
            <div class="col-md-6">
                <h2>Submit Service Request</h2>
                <form method="post"  enctype="multipart/form-data">
                    {% csrf_token %}
                    <label for="id_request_type" class="form-label">Service Request Type:</label>
                    <select name="request_type" id="id_request_type" class="form-select" aria-label="Default select example">
                        {% for value, label in form.fields.request_type.choices %}
                            <option value="{{ value }}">{{ label }}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <label for="id_details" class="form-label">Details:</label>
                    <textarea name="details" id="id_details" class="form-control"></textarea>
                    <br>
                    <label for="id_attachment" class="form-label">Attachment:</label>
                    <input type="file" name="attachment" id="id_attachment" class="form-control">
                    <br>
                    <button type="submit" class="form-control">Submit</button>
                </form>
             </div>
        </div>
</div>

{% endblock %}